name: build-images
on:
  workflow_call:
    inputs:
      dir:
        type: string
        required: true
jobs:
  validate-helm-charts:
    runs-on: ubuntu-latest
    outputs:
      num: ${{ steps.check.outputs.num_dir_changed }}
      dir: ${{ steps.check.outputs.end_dir }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check Changes
        id: "check"
        run: |
          changed_files="$(git show --pretty="" --name-only)"
          echo "$changed_files"
          dir_changed="$(echo "$changed_files" | xargs dirname | grep -o "${{ inputs.dir }}/[^/]*" | sort | uniq || true)"
          echo "---------------"
          echo "$dir_changed"
          num_dir_changed="$(echo "$dir_changed" | grep -c "${{ inputs.dir }}" || true)"
          echo "-----------"
          echo "$num_dir_changed"
          echo "=============="
          end_dir="$(echo "$dir_changed" | cut -d'/' -f2)"
          echo "end_dir=$end_dir" >> $GITHUB_OUTPUT
          echo "num_dir_changed=$num_dir_changed" >> $GITHUB_OUTPUT
      - if : ${{ steps.check.outputs.num_dir_changed > 0 }}
        run: |
          echo "Conditional-------------"
          echo ${{ steps.check.outputs.end_dir }}
  
  build-image:
    needs: validate-helm-charts
    if: ${{ needs.validate-helm-charts.outputs.num > 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: build Image
        run: |
          echo "This is test"
          echo ${{ needs.validate-helm-charts.outputs.dir }}
               
      - name: buid all
        uses: ./.github/workflows/release.yaml
        with:
          context: demo/${{ needs.validate-helm-charts.outputs.dir }}
          filepath: demo/${{ needs.validate-helm-charts.outputs.dir }}/Dockerfile
          tag: demo:0.0.0