name: dir-changes
on:
  push:
jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          json: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42.0.7
        with:
          dir_names: true
        
      - name: Get Changed Directories
        id: changed-directories
        uses: tj-actions/changed-files@v35
        with:
          fetch_depth: 0

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-directories.outputs.all_changed_and_modified_files }}; do
            echo $file
          done

  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.dirs)}}
    needs:
      - find-out-changes
    steps:
      - name: echo
        run: echo  "${{ matrix.dir }}"