name: Release Workflow

on:
  push:
    branches:
      - 'main'
permissions: write-all
  
jobs:
  release-job:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      created: ${{ steps.release.outputs.prs_created }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Release with release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
      - name: echo
        run: |
          echo "${{ steps.release.outputs.tag_name }}"
          echo "${{ steps.release.outputs.prs_created }}"
          echo "${{ steps.release.outputs.sha }}"
          echo "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
  tag:
    runs-on: ubuntu-latest
    needs: release-job
    if: needs.release-job.outputs.created == 'true'
    steps:
      - name: sec
        run: echo "${{ needs.release-job.outputs.tag }}"
          
#     # steps:
#     #   - name: Checkout
#     #     uses: actions/checkout@v4
#     #   - name: Semantic Release
#     #     uses: cycjimmy/semantic-release-action@v4
#     #     env:
#     #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
