name: Release Workflow

on:
  push:
    branches:
      - 'main'
      - 'prerelease'
permissions: write-all
  
jobs:
  release-job:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      created: ${{ steps.release.outputs.prs_created }}
      version: ${{ steps.release.outputs.pr }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Release with release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
      - name: echo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat package.json
          echo "------------"
          echo $(jq -r '.version' package.json)
          echo "-----------------"
          echo echo version=$(grep -oP '"version": *"[^/]*"' package.json) >> $GITHUB_OUTPUT
          echo "$version"
          echo "${{ steps.release.outputs.tag_name }}"
          echo "${{ steps.release.outputs.prs_created }}"
          echo "${{ steps.release.outputs.sha }}"
          echo "${{ steps.release.outputs.pr.number }}"
          echo "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          echo "------------//////"
          gh pr list --author "github-actions" --base "main" --label "autorelease:pending" --state "open"
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: echo
        run: cat package.json
      - name: PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT: ${{ github.ref }}
          COM:  ${{ github.sha }}
        run: |
          echo ${PR_URL##*/}
          gh pr checkout 38
          cat package.json
          echo ${PR_URL##*/}
          echo $GIT
          echo $COM
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - name: PR Lists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  # tag:
  #   runs-on: ubuntu-latest
  #   needs: release-job
  #   if: needs.release-job.outputs.created == 'true'
  #   strategy:
  #     matrix:
  #       charts: ${{ fromJSON(needs.release-job.outputs.version) }}
  #   steps:
  #     - name: sec
  #       run: echo "${{ matrix.charts }}"
          
#     # steps:
#     #   - name: Checkout
#     #     uses: actions/checkout@v4
#     #   - name: Semantic Release
#     #     uses: cycjimmy/semantic-release-action@v4
#     #     env:
#     #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
