name: Release Workflow

on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: helm
          default-branch: main
#     # steps:
#     #   - name: Checkout
#     #     uses: actions/checkout@v4
#     #   - name: Semantic Release
#     #     uses: cycjimmy/semantic-release-action@v4
#     #     env:
#     #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
